//! "Delete browsing data" — Brave's destructive privacy action, adapted for
//! offline use while Brave is closed.
//!
//! A `DataCategory` lists exactly which files and directories back a UI option
//! on `brave://settings/privacy/delete-browsing-data`. The tool never touches
//! anything outside these lists. Paths ending with `/` are directories whose
//! *contents* are removed (the directory itself stays in place so Brave can
//! recreate files on next launch without running into permission surprises).
//!
//! Every category is conservative — it deliberately leaves state Brave cannot
//! regenerate alone. In particular these are NEVER in any category:
//!
//!   - `Bookmarks`, `Bookmarks.bak`       (user content)
//!   - `Preferences`, `Secure Preferences` (shield + privacy settings)
//!   - `Extensions/`, `Local Extension Settings/` (installed extensions)
//!   - `Sync Data/`                        (sync handshake state)
//!
//! On Linux some paths live under `~/.cache/BraveSoftware/...` rather than the
//! config dir, so the clear/size functions try both the profile dir and the
//! channel's `cache_root/<profile>/` for each target.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::paths::ChannelPaths;
use crate::profile::Profile;

#[derive(Debug, Clone, Copy)]
pub struct DataCategory {
    pub id: &'static str,
    pub label: &'static str,
    pub desc: &'static str,
    /// Targets relative to the profile directory. A trailing `/` means the
    /// directory's *contents* should be wiped (the directory remains).
    pub targets: &'static [&'static str],
    /// Default checkbox state — mirrors Brave's own defaults on the
    /// "Delete browsing data" dialog.
    pub default_checked: bool,
}

pub const CATEGORIES: &[DataCategory] = &[
    // -----------------------------------------------------------------
    // Browsing history — visited URLs, autocomplete history, favicons.
    //
    // Brave's UI copy says "Clears history, including in the search box".
    // The History SQLite DB also holds download history, so we document that
    // deleting this category removes both. Favicons and visited-link hashes
    // live in adjacent DBs and get wiped together so the "visited" styling
    // in the UI doesn't show ghost entries for URLs we just forgot.
    // -----------------------------------------------------------------
    DataCategory {
        id: "history",
        label: "Browsing history",
        desc: "History DB (also removes download history — same SQLite file). \
               Visited-links, favicons, and autocomplete predictor DBs are \
               included so the new-tab UI doesn't show stale entries.",
        targets: &[
            "History",
            "History-journal",
            "History Provider Cache",
            "Visited Links",
            "Top Sites",
            "Top Sites-journal",
            "Favicons",
            "Favicons-journal",
            "Network Action Predictor",
            "Network Action Predictor-journal",
        ],
        default_checked: true,
    },
    // -----------------------------------------------------------------
    // Cookies and other site data — per-origin persistent storage that
    // identifies you to sites. Everything here is regenerated by sites as
    // you browse; nothing here is user content.
    //
    //   Cookies*                — HTTP cookies
    //   Network/Cookies*        — modern Chromium cookie store
    //   Network/Trust Tokens*   — anti-fraud tokens
    //   Network/Reporting and NEL* — network error logging
    //   Local Storage/          — window.localStorage
    //   Session Storage/        — window.sessionStorage persisted across restarts
    //   IndexedDB/              — large structured per-site storage
    //   File System/            — OPFS (origin private file system)
    //   Shared Dictionary/      — compression dictionaries
    //   databases/              — legacy WebSQL
    //   QuotaManager*           — quota accounting
    //   WebStorage/             — compat leftovers
    // -----------------------------------------------------------------
    DataCategory {
        id: "cookies",
        label: "Cookies and other site data",
        desc: "Cookies, localStorage/sessionStorage, IndexedDB, OPFS, compression \
               dictionaries, quota accounting, Trust Tokens and Reporting/NEL. \
               Signs you out of every site; site login state, in-site settings, \
               and per-site notification permissions are lost.",
        targets: &[
            "Cookies",
            "Cookies-journal",
            "Network/Cookies",
            "Network/Cookies-journal",
            "Network/Trust Tokens",
            "Network/Trust Tokens-journal",
            "Network/Reporting and NEL",
            "Network/Reporting and NEL-journal",
            "Local Storage/",
            "Session Storage/",
            "IndexedDB/",
            "File System/",
            "Shared Dictionary/",
            "databases/",
            "QuotaManager",
            "QuotaManager-journal",
            "WebStorage/",
        ],
        default_checked: true,
    },
    // -----------------------------------------------------------------
    // Cached images and files — everything the browser regenerates from
    // network requests. Safe to wipe at any time; the only "loss" is that
    // the next page load is slower until the cache refills.
    //
    //   Cache/                  — main HTTP disk cache
    //   Code Cache/             — compiled JS / Wasm bytecode
    //   GPUCache/               — shader and program cache
    //   DawnGraphiteCache/      — Dawn backend (Graphite) shader cache
    //   DawnWebGPUCache/        — WebGPU shader cache
    //   Service Worker/CacheStorage/ — SW-managed CacheStorage entries
    //   Service Worker/ScriptCache/  — SW JS blobs
    //   Service Worker/Database/     — SW metadata / registration DB
    //   Storage/ext/            — extension-managed staging cache
    // -----------------------------------------------------------------
    DataCategory {
        id: "cache",
        label: "Cached images and files",
        desc: "Network cache, compiled JS/Wasm bytecode, GPU/WebGPU shader caches, \
               Service Worker cache storage + script blobs + metadata DB, and \
               extension storage staging cache. All regenerated on demand — safe \
               to clear any time.",
        targets: &[
            "Cache/",
            "Code Cache/",
            "GPUCache/",
            "DawnGraphiteCache/",
            "DawnWebGPUCache/",
            "Service Worker/CacheStorage/",
            "Service Worker/ScriptCache/",
            "Service Worker/Database/",
            "Storage/ext/",
        ],
        default_checked: true,
    },
    // -----------------------------------------------------------------
    // Passwords and other sign-in data — Chromium's "Login Data" SQLite DB.
    //
    // Off by default because deletion is irreversible and Brave offers no
    // per-row export from the offline file. Use `brave://password-manager`
    // to export first if you want a copy.
    // -----------------------------------------------------------------
    DataCategory {
        id: "passwords",
        label: "Passwords and other sign-in data",
        desc: "The Login Data SQLite DB(s). IRRECOVERABLE once deleted — export \
               from brave://password-manager first if you want a backup.",
        targets: &[
            "Login Data",
            "Login Data-journal",
            "Login Data For Account",
            "Login Data For Account-journal",
        ],
        default_checked: false,
    },
    // -----------------------------------------------------------------
    // Autofill form data — the "Web Data" DB stores addresses, credit cards,
    // saved form entries, custom search engines, and sync metadata. Wiping
    // this removes ALL of those, not just form history. Off by default.
    // -----------------------------------------------------------------
    DataCategory {
        id: "autofill",
        label: "Autofill form data",
        desc: "Web Data SQLite DB(s): addresses, credit cards, saved form \
               entries, AND custom search engines. Wipes everything stored in \
               these files together.",
        targets: &[
            "Web Data",
            "Web Data-journal",
            "Web Data For Account",
            "Web Data For Account-journal",
        ],
        default_checked: false,
    },
];

#[derive(Debug, Default)]
pub struct ClearReport {
    pub touched_paths: Vec<PathBuf>,
    pub skipped: Vec<(PathBuf, String)>,
    pub bytes_freed: u64,
}

/// Dry-run size computation for a category. Walks every target and sums the
/// on-disk bytes; zero if none of the targets exist.
pub fn size_of(paths: &ChannelPaths, profile: &Profile, cat: &DataCategory) -> u64 {
    let mut total = 0;
    for tgt in cat.targets {
        for root in candidate_roots(paths, profile) {
            total += target_size(&root, tgt);
        }
    }
    total
}

/// Delete the category's targets. On `dry_run`, only sizes are computed.
pub fn clear(
    paths: &ChannelPaths,
    profile: &Profile,
    cat: &DataCategory,
    dry_run: bool,
) -> Result<ClearReport> {
    let mut report = ClearReport::default();
    // Some targets live under the profile dir on Windows/macOS but under a
    // separate cache root on Linux; try both and dedupe.
    let roots = candidate_roots(paths, profile);

    for tgt in cat.targets {
        let trimmed = tgt.trim_end_matches('/');
        let is_dir_contents = tgt.ends_with('/');
        let mut done_paths: Vec<PathBuf> = Vec::new();
        for root in &roots {
            let p = root.join(trimmed);
            // Skip dupes across identical roots (Windows/macOS case).
            if done_paths.contains(&p) {
                continue;
            }
            done_paths.push(p.clone());
            if !p.exists() {
                continue;
            }
            let size = target_size(root, tgt);
            if dry_run {
                report.touched_paths.push(p);
                report.bytes_freed += size;
                continue;
            }
            let res = if is_dir_contents || p.is_dir() {
                clear_dir_contents(&p)
            } else {
                std::fs::remove_file(&p).with_context(|| format!("removing {}", p.display()))
            };
            match res {
                Ok(()) => {
                    report.touched_paths.push(p);
                    report.bytes_freed += size;
                }
                Err(e) => report.skipped.push((p, e.to_string())),
            }
        }
    }
    Ok(report)
}

fn candidate_roots(paths: &ChannelPaths, profile: &Profile) -> Vec<PathBuf> {
    let mut roots = vec![profile.path.clone()];
    let cache_profile = paths.cache_root.join(&profile.dir_name);
    if cache_profile != profile.path {
        roots.push(cache_profile);
    }
    roots
}

fn target_size(base: &Path, tgt: &str) -> u64 {
    let trimmed = tgt.trim_end_matches('/');
    let p = base.join(trimmed);
    if !p.exists() {
        return 0;
    }
    if p.is_file() {
        std::fs::metadata(&p).map(|m| m.len()).unwrap_or(0)
    } else {
        walkdir::WalkDir::new(&p)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_type().is_file())
            .filter_map(|e| e.metadata().ok())
            .map(|m| m.len())
            .sum()
    }
}

fn clear_dir_contents(dir: &Path) -> Result<()> {
    for entry in std::fs::read_dir(dir)
        .with_context(|| format!("reading {}", dir.display()))?
    {
        let entry = entry?;
        let p = entry.path();
        if entry.file_type()?.is_dir() {
            std::fs::remove_dir_all(&p)
                .with_context(|| format!("removing dir {}", p.display()))?;
        } else {
            std::fs::remove_file(&p)
                .with_context(|| format!("removing file {}", p.display()))?;
        }
    }
    Ok(())
}

pub fn lookup(id: &str) -> Option<&'static DataCategory> {
    CATEGORIES.iter().find(|c| c.id.eq_ignore_ascii_case(id))
}

/// Friendly byte-size label: 0 B / 12.34 MiB / etc.
pub fn format_bytes(n: u64) -> String {
    const UNITS: &[&str] = &["B", "KiB", "MiB", "GiB", "TiB"];
    let mut v = n as f64;
    let mut i = 0;
    while v >= 1024.0 && i < UNITS.len() - 1 {
        v /= 1024.0;
        i += 1;
    }
    if i == 0 {
        format!("{} {}", n, UNITS[i])
    } else {
        format!("{:.2} {}", v, UNITS[i])
    }
}
